title: Torchbearer Lab
# This "permalink" line forces a simple structure
permalink: /:title/
baseurl: "/torchbearerlab.github.io"
url: "https://meredithclikkie.github.io"
remote_theme: pages-themes/minimal@v0.2.0

# This ensures the build isn't skipping your posts
collections:
  posts:
    output: true
